services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-twin-app
    restart: unless-stopped
    ports:
      - "9350:9350"
    environment:
      NODE_ENV: production
      PORT: "9350"
      HOSTNAME: 0.0.0.0
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24
